---
apiVersion: v1
data:
  # setting to 0, but 0 is base64 encoded
  NODE_TLS_REJECT_UNAUTHORIZED: MA==
  RHDH_TOKEN: base64-encoded-token-generated-from-openssl-or-similar-program
kind: Secret
metadata:
  name: ai-rh-developer-hub-env
  namespace: ai-rhdh
type: Opaque

