kind: ConfigMap
apiVersion: v1
metadata:
  # There will be a pre-existing dynamic plugins already present if you followed the installer
  # in which case, modify the existing configmap to add the plugin entry in
  name: backstage-ai-rh-developer-hub-dynamic-plugins-3c140ae5afb4
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    # The following specifies that the model catalog plugin (red-hat-developer-hub-backstage-plugin-catalog-backend-module-model-catalog)
    # contained within the OCI archive (quay.io/redhat-ai-dev/ai-integrations-rhdh:latest) should be installed into RHDH
    # officially built images are at oci://quay.io/redhat-ai-dev/ai-integrations-rhdh:latest but 
    # the 'consolidate-ai-catalog-extensions' branch from the gabemontero fork of the plugins produced these plugin images 
    # allow for push import with sidecars
    plugins:
      - disabled: false
        package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-catalog-backend-module-model-catalog:next__0.6.0!red-hat-developer-hub-backstage-plugin-catalog-backend-module-model-catalog
      - disabled: false
        package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-catalog-techdoc-url-reader-backend:next__0.3.0!red-hat-developer-hub-backstage-plugin-catalog-techdoc-url-reader-backend
#      - package: oci://quay.io/gabemontero/ai-experience:latest!red-hat-developer-hub-backstage-plugin-catalog-backend-module-model-catalog
#        disabled: false
#      - package: oci://quay.io/gabemontero/ai-experience:latest!red-hat-developer-hub-backstage-plugin-catalog-techdoc-url-reader-backend
#        disabled: false
#      - package: oci://quay.io/gabemontero/ai-experience:latest!red-hat-developer-hub-backstage-plugin-catalog-backend-module-model-catalog-location-extension
#        disabled: false
#      - package: oci://quay.io/gabemontero/ai-experience:latest!red-hat-developer-hub-backstage-plugin-catalog-backend-module-model-catalog-reader
#        disabled: false
