# This is a basic workflow to help you get started with Actions

name: Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: 1.23.x
          cache: true
          check-latest: true

      # Runs a single command using the runners shell
      - name: unit test
        run: make test

  validate-schema:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # Validate the JSON schemas
      - name: Validate model catalog JSON schema
        uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          schema: json-schema
          files: schema/model-catalog.schema.json

      # Run tests against the schema
      - name: Test the model catalog JSON schema
        uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          schema: schema/model-catalog.schema.json
          files: schema/tests/*.json

      - name: Generate types, and ensure latest changes were committed
        run: |
          make install-quicktype
          make generate-types-all
          if [[ ! -z $(git status -s) ]]
          then
            echo 'Command `make generate-types-all` did introduce changes, which should not be the case if it had been run as part of the PR. Please run it locally and check in the results as part of your PR.'
            git --no-pager diff
            exit 1
          fi

  build-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build Container Images
        run: |
          make build-containers